version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
            - /var/www/vendor
            - /var/www/node_modules
        depends_on:
            - mysql
            - redis
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:alpine
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
